// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirEBVhSdKoA3e4brSXkWd1QERjNmmJL4',
    appId: '1:1062909429402:web:6ade3972824c5772b0c123',
    messagingSenderId: '1062909429402',
    projectId: 'chatapp-49147',
    authDomain: 'chatapp-49147.firebaseapp.com',
    storageBucket: 'chatapp-49147.appspot.com',
    measurementId: 'G-8X9N4LLDQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7cTQgzgZOykIKYhge_Uvn-ixqSm9PYI',
    appId: '1:1062909429402:android:9d337116fc9877fcb0c123',
    messagingSenderId: '1062909429402',
    projectId: 'chatapp-49147',
    storageBucket: 'chatapp-49147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIlbPFUfWorfBrwY0IZoxdXDg__zG6As0',
    appId: '1:1062909429402:ios:cad9654195810a74b0c123',
    messagingSenderId: '1062909429402',
    projectId: 'chatapp-49147',
    storageBucket: 'chatapp-49147.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

}